name : Foundation5/github pages/Jykill starter/portfolio
brand : Daniel Kirkeng
description : Portfolio til Daniel Kirkeng.
keyword : portfolio, Daniel Kirkeng
url : http://danielkirkeng.github.io/
email : daniel@kirkeng.net
twitter : danielkirkeng
github : danielkirkeng
author : Daniel Kirkeng
year : 2016
markdown : kramdown
exclude :
  - node_modules
